### ISSUE TITLE
Chrome launched, but didn't give a WebSocket URL before we timed out

### ISSUE THREAD

**Issue by abhijithpa** [iustin24/chameleon#18] opened 2022-11-15 14:36 UTC
Hi, I have run into an issue launching chameleon with tech scan.

command: chameleon -u http://testphp.vulnweb.com/  -a

error: "/root/.local/share/headless-chrome/linux-634997.zip"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', /cargo/git/checkouts/wappalyzer-e32a3fb79f4ccad3/fb82bb4/src/lib.rs:98:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

running apt-get install libxss1 doesn't seem to fix the issue.

**Comment by hax0rgb** [comment] 2022-12-12 10:57
Same issue observed. Do we have any updates on this one?

**Comment by iustin24** [comment] 2022-12-12 11:20
Hi @hax0rgb 

This issue is a duplicate of https://github.com/iustin24/chameleon/issues/8. Did you follow the steps there?
If you did and are still getting the same issue, please comment on the other Github Issue. Add the OS you are trying it on and rust version.

Thanks!

**Closed as not planned by iustin24** 2022-12-12 11:20 UTC
Labels: duplicate

**Comment by hax0rgb** [comment] 2022-12-12 13:03
Worked. All I needed was to install headless chrome.
